{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-ui",
    "version": "1.11.0-alpha01-fongmi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-danmaku",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.0-alpha01-fongmi.aar",
          "url": "media3-ui-1.11.0-alpha01-fongmi.aar",
          "size": 436101,
          "sha512": "e96fd8d4530b8c7cfcb8fb3e91e7aaf681285b49fe222e9dd5896509a641c57b102122df1aa77a48c31239d36a63194a438be232b38217628cf4d31ebd9114f4",
          "sha256": "4f16fa9b572dc229dfcb6e68daa98964e32b588f651d6c7475aaaa029cdc1bfa",
          "sha1": "0e3ba00f2af988e468392e266788eb02b6f9527c",
          "md5": "2cef8ee4251190f8aecb122cb1db8395"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-danmaku",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-ui-1.11.0-alpha01-fongmi.aar",
          "url": "media3-ui-1.11.0-alpha01-fongmi.aar",
          "size": 436101,
          "sha512": "e96fd8d4530b8c7cfcb8fb3e91e7aaf681285b49fe222e9dd5896509a641c57b102122df1aa77a48c31239d36a63194a438be232b38217628cf4d31ebd9114f4",
          "sha256": "4f16fa9b572dc229dfcb6e68daa98964e32b588f651d6c7475aaaa029cdc1bfa",
          "sha1": "0e3ba00f2af988e468392e266788eb02b6f9527c",
          "md5": "2cef8ee4251190f8aecb122cb1db8395"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-ui-1.11.0-alpha01-fongmi-sources.jar",
          "url": "media3-ui-1.11.0-alpha01-fongmi-sources.jar",
          "size": 121580,
          "sha512": "a01d15909cc9e222d5db93a4cf9d7d0fc780f816db1549f12e3d6939c6ddac5121b04396beb61165c9b6ffe5733d80cbaa4629b455be2e9566fcf0b5f400d02f",
          "sha256": "dc6eb9410c2ffa7f19c1c6dfb783915cba9b71199c4d48ccccf1005ffaf32ece",
          "sha1": "3eeca6bb72b0a3208762acb0770a95a56c0d419a",
          "md5": "4900642e652b80759878706a5dd97015"
        }
      ]
    }
  ]
}
