{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-extractor",
    "version": "1.11.0-alpha01-fongmi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0-alpha01-fongmi.aar",
          "url": "media3-extractor-1.11.0-alpha01-fongmi.aar",
          "size": 1004367,
          "sha512": "745f2256f35477bb3b510a91bdd537066b2cc8f9bd7b4742417f260e454ffa142addd5c170e7a2167a3561e40bec993bb23c6584e293083c5d8cd7dd239276ac",
          "sha256": "d97b5a0934a04c38a6f3b3ee83692ef23ef09670982c8f028c6084e15e9e895d",
          "sha1": "60d5ad2a12aa6d00313b61be76ad29dcdc18cb68",
          "md5": "24c402e082739b6527f4ee7e6088553e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.googlecode.juniversalchardet",
          "module": "juniversalchardet",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-extractor-1.11.0-alpha01-fongmi.aar",
          "url": "media3-extractor-1.11.0-alpha01-fongmi.aar",
          "size": 1004367,
          "sha512": "745f2256f35477bb3b510a91bdd537066b2cc8f9bd7b4742417f260e454ffa142addd5c170e7a2167a3561e40bec993bb23c6584e293083c5d8cd7dd239276ac",
          "sha256": "d97b5a0934a04c38a6f3b3ee83692ef23ef09670982c8f028c6084e15e9e895d",
          "sha1": "60d5ad2a12aa6d00313b61be76ad29dcdc18cb68",
          "md5": "24c402e082739b6527f4ee7e6088553e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-extractor-1.11.0-alpha01-fongmi-sources.jar",
          "url": "media3-extractor-1.11.0-alpha01-fongmi-sources.jar",
          "size": 848082,
          "sha512": "1723bf5c9314bc1f8308eefe03b5313b764c03fb1aa277bd52c4d3272537759fc3d33e4f620237412adadb413a8674943430a9eefc10b0e90ba323c4d2b1f38f",
          "sha256": "0e19dc368b08edd2ddf754b51a960583313458e72f2e842067f41c6718234e90",
          "sha1": "ec1fbe86c3d992c396ace8c031b01f6085ba5f19",
          "md5": "caf95bc307bf79b3970c2717fcb795af"
        }
      ]
    }
  ]
}
