{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-datasource-okhttp",
    "version": "1.11.0-alpha01-fongmi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-alpha01-fongmi.aar",
          "url": "media3-datasource-okhttp-1.11.0-alpha01-fongmi.aar",
          "size": 9841,
          "sha512": "7299c89afd3f8ed618f701c32a063e5e89ca3c198006cc4a0df310958ca4dfbf3c8445a6ee5448f90cb3f320c1c66ab6e3cbacd053a6fe2fd2f9454de6adf766",
          "sha256": "5ae49107782c360bd94c2796046acae9f5f09f29934367414c9bc87bdd754bed",
          "sha1": "5290f3a1e47b7903c9d85cca1875a8f6d8e989b2",
          "md5": "f98fffcd5c290cfc20d150c84ca9c77b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "4.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-alpha01-fongmi.aar",
          "url": "media3-datasource-okhttp-1.11.0-alpha01-fongmi.aar",
          "size": 9841,
          "sha512": "7299c89afd3f8ed618f701c32a063e5e89ca3c198006cc4a0df310958ca4dfbf3c8445a6ee5448f90cb3f320c1c66ab6e3cbacd053a6fe2fd2f9454de6adf766",
          "sha256": "5ae49107782c360bd94c2796046acae9f5f09f29934367414c9bc87bdd754bed",
          "sha1": "5290f3a1e47b7903c9d85cca1875a8f6d8e989b2",
          "md5": "f98fffcd5c290cfc20d150c84ca9c77b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-datasource-okhttp-1.11.0-alpha01-fongmi-sources.jar",
          "url": "media3-datasource-okhttp-1.11.0-alpha01-fongmi-sources.jar",
          "size": 6321,
          "sha512": "4e5fe00ddb459e59624a55c242b9bab03b8d1ca40091b04235b8e61c880116f9e204bf9d5c1b2e3dbfe8c65ae1e633ea6cb490467aa6fc43069d7c052ae8c9b8",
          "sha256": "d299889968e426adc5c6f13510da0e4ab110085ec408c92cc23e64cab696f45b",
          "sha1": "4d13e9d0dd4bc0415961e5c2b7849bdce0da00dd",
          "md5": "364ebb366241636cc22f2c9d7235c0b5"
        }
      ]
    }
  ]
}
