{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-common",
    "version": "1.11.0-alpha01-fongmi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0-alpha01-fongmi.aar",
          "url": "media3-common-1.11.0-alpha01-fongmi.aar",
          "size": 653564,
          "sha512": "6fa424ad68d4d72a97888a70ab94098e4a097394d3d126b47cd84af56a81434d23a24000a557d2f09ce98dfbefc08742423e2c1c55b5ce832ed1f18871552ebc",
          "sha256": "c886b3465dda48de13bb21c7589ce5f7a2901398cbdcaee116ffeb83d4e12b7c",
          "sha1": "c1db913e0e518dfcd7ed1b6ae11f9319394af504",
          "md5": "bc858e157eb2c9028b3debdf8b15693d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.3.1-android"
          },
          "excludes": [
            {
              "group": "com.google.j2objc",
              "module": "j2objc-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-compat-qual"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "org.codehaus.mojo",
              "module": "animal-sniffer-annotations"
            },
            {
              "group": "org.checkerframework",
              "module": "checker-qual"
            },
            {
              "group": "com.google.errorprone",
              "module": "error_prone_annotations"
            }
          ]
        },
        {
          "group": "androidx.annotation",
          "module": "annotation-experimental",
          "version": {
            "requires": "1.3.1"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.media3",
          "module": "media3-cast",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-common-ktx",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-container",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-database",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-cronet",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-ktor",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-okhttp",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-datasource-rtmp",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-decoder",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-av1",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-ffmpeg",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-flac",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-iamf",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-midi",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-mpegh",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-opus",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-decoder-vp9",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-effect-lottie",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "lib-effect-ndk",
          "version": {
            "requires": "unspecified"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-ima",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-workmanager",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-extractor",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-inspector-frame",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-muxer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-session",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-transformer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-danmaku",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-compose-material3",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-ui-leanback",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-test-utils-robolectric",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-common-1.11.0-alpha01-fongmi.aar",
          "url": "media3-common-1.11.0-alpha01-fongmi.aar",
          "size": 653564,
          "sha512": "6fa424ad68d4d72a97888a70ab94098e4a097394d3d126b47cd84af56a81434d23a24000a557d2f09ce98dfbefc08742423e2c1c55b5ce832ed1f18871552ebc",
          "sha256": "c886b3465dda48de13bb21c7589ce5f7a2901398cbdcaee116ffeb83d4e12b7c",
          "sha1": "c1db913e0e518dfcd7ed1b6ae11f9319394af504",
          "md5": "bc858e157eb2c9028b3debdf8b15693d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-common-1.11.0-alpha01-fongmi-sources.jar",
          "url": "media3-common-1.11.0-alpha01-fongmi-sources.jar",
          "size": 532541,
          "sha512": "da96d7f7597565a41c5f467aa6aef44392136b189793ab9cdde55caec8fb69cd3ce973c3ac725caa1a07dc77400a5e267dbbb33b4cb89021e689d2f8a974e428",
          "sha256": "eefdb2048ad1f013fdf7bb71a581e0e922119acc6f408b59de05391b92840d89",
          "sha1": "903f21477216f84cf471d198b7fd201fe8b60c91",
          "md5": "e902605591ed390537455f4a9a907d1b"
        }
      ]
    }
  ]
}
