{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-dash",
    "version": "1.11.0-alpha01-fongmi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.11.0-alpha01-fongmi.aar",
          "url": "media3-exoplayer-dash-1.11.0-alpha01-fongmi.aar",
          "size": 147708,
          "sha512": "8b0d57afd2aad3df67dbc602453f52b9fb31ac96be1b1badfc3b1478df83426e08fc1361e17a36e07dc2aa6c3de690c30907948e1b79df9809de02b7a0d838f8",
          "sha256": "07f3e0df2660fa5622b8c4cad1820fe2e63763606df9e5c27c4ebad60f23fe3f",
          "sha1": "32074bfe071e8dc72d080f51dec9eec8a632639a",
          "md5": "8f20d0130213254b17716cfc8149eceb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-dash-1.11.0-alpha01-fongmi.aar",
          "url": "media3-exoplayer-dash-1.11.0-alpha01-fongmi.aar",
          "size": 147708,
          "sha512": "8b0d57afd2aad3df67dbc602453f52b9fb31ac96be1b1badfc3b1478df83426e08fc1361e17a36e07dc2aa6c3de690c30907948e1b79df9809de02b7a0d838f8",
          "sha256": "07f3e0df2660fa5622b8c4cad1820fe2e63763606df9e5c27c4ebad60f23fe3f",
          "sha1": "32074bfe071e8dc72d080f51dec9eec8a632639a",
          "md5": "8f20d0130213254b17716cfc8149eceb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-dash-1.11.0-alpha01-fongmi-sources.jar",
          "url": "media3-exoplayer-dash-1.11.0-alpha01-fongmi-sources.jar",
          "size": 100496,
          "sha512": "412ca3acc4aacbcb52b5119569e0d32aa04195d42127131e36eb8a219abed0700a891e54900b0c5a1478891a745af816c360d2f81f241c2908ce1b4683c305b2",
          "sha256": "403665d4f04520e83bba7ecfa9b403848b6d9da841e7380937662053bed6e2c6",
          "sha1": "8fdc7c533b3937438bd96683b0903a8255413eab",
          "md5": "11a6f89bb05a7075add83719d9b83d29"
        }
      ]
    }
  ]
}
