{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.media3",
    "module": "media3-exoplayer-hls",
    "version": "1.11.0-alpha01-fongmi",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.1.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.11.0-alpha01-fongmi.aar",
          "url": "media3-exoplayer-hls-1.11.0-alpha01-fongmi.aar",
          "size": 276447,
          "sha512": "97af022f1750e25e1b1d60652a9263f5c863ca71958c96a5cdafb4081b730204ffb53726dc06bf41dcb28c75d7f845aff66f247d86a23f83e4c29b9832ee2930",
          "sha256": "99fe816a319ee8a3033bedcbdeeb77a130e3f1ef13557e3ca42be800ff96e807",
          "sha1": "4381598e15cd2ac12803664aeadb52eac11dfae9",
          "md5": "ca7023f3958ded4ccfec4ef20466ebd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.11.0-alpha01-fongmi"
          }
        }
      ],
      "files": [
        {
          "name": "media3-exoplayer-hls-1.11.0-alpha01-fongmi.aar",
          "url": "media3-exoplayer-hls-1.11.0-alpha01-fongmi.aar",
          "size": 276447,
          "sha512": "97af022f1750e25e1b1d60652a9263f5c863ca71958c96a5cdafb4081b730204ffb53726dc06bf41dcb28c75d7f845aff66f247d86a23f83e4c29b9832ee2930",
          "sha256": "99fe816a319ee8a3033bedcbdeeb77a130e3f1ef13557e3ca42be800ff96e807",
          "sha1": "4381598e15cd2ac12803664aeadb52eac11dfae9",
          "md5": "ca7023f3958ded4ccfec4ef20466ebd6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "media3-exoplayer-hls-1.11.0-alpha01-fongmi-sources.jar",
          "url": "media3-exoplayer-hls-1.11.0-alpha01-fongmi-sources.jar",
          "size": 181521,
          "sha512": "5bc1f814508e4716afde1afba66c2faa7e979572fffabc3bfb70fb0f16c91ed37a3f441e5432aa11a07c57ca725934197f5644f09828d2cf4d59e3bacb1e7715",
          "sha256": "ac4dc855c204407b41c27427d56b3f0817310ac1c7da33766d42648481cd74b6",
          "sha1": "12feaa3ea8eccd931c3fade9a349238c319c45ac",
          "md5": "7dd3bf860697dee3a7474049b917377c"
        }
      ]
    }
  ]
}
